host = "127.0.0.1"
port = 4000
user = "root"
password = ""

[suite]
names = ["bank"]
concurrency = 10000

[suite.bank]
num_accounts = 100000000
interval = "2s"
table_num = 1

[metric]
job = "stability_test"
address = ""
interval = "5s"
