#!/usr/bin/expect -f

spawn ssh q2
expect "#*"
send "cd /home/pingcap/deploy\r"
send "nohup ./tikv.sh </dev/null >/dev/null 2>&1& \r"
send "exit\r"
expect eof

spawn ssh q3
expect "#*"
send "cd /home/pingcap/deploy\r"
send "nohup ./tikv.sh </dev/null >/dev/null 2>&1& \r"
send "exit\r"
expect eof

spawn ssh q4
expect "#*"
send "cd /home/pingcap/deploy\r"
send "nohup ./tikv.sh </dev/null >/dev/null 2>&1& \r"
send "exit\r"
expect eof

